### ISSUE TITLE
Ошибка WebDriver manager

### ISSUE THREAD

**Issue by jiumohoo** [qulled/parser_margin#1]
Здравствуй. Я не знаю phyton, но случайно нашёл через поиск гитхаба этот репозиторий.
Установил phyton, pycharm. Разобрался, как запустить requirements.txt чтобы те скачались. Далее я в ауте...  
В коде поменял пусть сохранения на свой. 

При запуске любого из get_report_magin_буква_chrome 
В консоле одна и та же ошибка. Увы, не смогу победить. 
**Можешь ли помочь, если конечно не жалко потратить время объяснив, что не так? Так-то очень полезно перекачать все детализированные отчёты. Вручную долго.** 

_**Я ведь верно понял, что оно все отчёты качает? Разве что в коде не вижу ничего связанного похожего на async и парсинг из  всех отчётов.**_

C:\Users\Максим\Desktop\parser_margin-main\venv\Scripts\python.exe C:/Users/Максим/Desktop/parser_margin-main/get_report_margin_B_chrome.py
[WDM] - ====== WebDriver manager ======

[WDM] - Current google-chrome version is 103.0.5060
[WDM] - Get LATEST chromedriver version for 103.0.5060 google-chrome
[WDM] - Driver [C:\Users\Максим\.wdm\drivers\chromedriver\win32\103.0.5060.53\chromedriver.exe] found in cache
Traceback (most recent call last):
  File "C:\Users\Максим\Desktop\parser_margin-main\get_report_margin_B_chrome.py", line 28, in <module>
    driver = webdriver.Chrome(options=options,service=Service(ChromeDriverManager().install()))
  File "C:\Users\Максим\Desktop\parser_margin-main\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Максим\Desktop\parser_margin-main\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Максим\Desktop\parser_margin-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Максим\Desktop\parser_margin-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Максим\Desktop\parser_margin-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Максим\Desktop\parser_margin-main\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to create Chrome process.
Stacktrace:
Backtrace:
	Ordinal0 [0x00596463+2188387]
	Ordinal0 [0x0052E461+1762401]
	Ordinal0 [0x00443D78+802168]
	Ordinal0 [0x00460CB4+920756]
	Ordinal0 [0x0045E331+910129]
	Ordinal0 [0x00491430+1119280]
	Ordinal0 [0x0049108A+1118346]
	Ordinal0 [0x0048C5F6+1099254]
	Ordinal0 [0x00466BE0+945120]
	Ordinal0 [0x00467AD6+948950]
	GetHandleVerifier [0x008371F2+2712546]
	GetHandleVerifier [0x0082886D+2652765]
	GetHandleVerifier [0x0062002A+520730]
	GetHandleVerifier [0x0061EE06+516086]
	Ordinal0 [0x0053468B+1787531]
	Ordinal0 [0x00538E88+1805960]
	Ordinal0 [0x00538F75+1806197]
	Ordinal0 [0x00541DF1+1842673]
	BaseThreadInitThunk [0x76E5FA29+25]
	RtlGetAppContainerNamedObjectPath [0x778E7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x778E7A6E+238]

**Comment by qulled** [comment]
Привет! Тут надо разбить ответ на несколько частей:
1) Дело в том, что данный парсер настроен под определенный куки с аутентификацией личного кабинета (в репозитарии он не за лит по соображениям безопасности), но это не отменяет того факта, что ты можешь создать собственный файл куки. Тут наверное лучше будет по гуглить как это делается, но в кратце также через selenium.
p.s.
он не заработает если его просто скопируешь, даже с правильным указанием путей, нужен файл куки который ты предварительно запишешь при авторизации на сайт личного кабинета с телефоном и смс.

2) После того когда у тебя будет файл который позволит авторизоваться в личный кабинет, ты можешь донастроить парсер под себя, так как в настоящее время он качает только самый последний подгруженный парсер (в верху списка который), но ты можешь написать чтобы качались все.

3) Если с винды создаешь путь, то тут три варианта вида написания пути:
а) "C://User//Downloads//......." двойные косые
б) "C:\User\Downloads\......" обратные косые
в) r"C:/User/Downloads/......" обычные косые, но с аргументом 'r' который сам устанавливает верные косые для парсера

**Comment by jiumohoo** [comment]
Увы, думал код парсит все детализированные. Не подходит :( Дописать точно не в состоянии. 
ВБ обожает редактировать формат старых отчётов. Постоянно меняются названия городов, добавляются обоснования для оплаты и всякое другое. 
Как раз-таки про куки тоже был вопрос, думал оно из браузера берёт данные хрома (залогинен (много себе навоображал)).
Поскольку для доступа на портал поставщика для "аутентификации" требуется в заголовке запроса только кука, то зачем заморачиваться с подготовительным файлом? Проще его руками вписать, разве не так?
